# Generated by Django 5.1.3 on 2024-11-22 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_name",
                    models.CharField(
                        default="Подписка",
                        help_text="Укажите название подписки",
                        max_length=100,
                        verbose_name="Подписка",
                    ),
                ),
                (
                    "subscription_sign",
                    models.BooleanField(default=False, verbose_name="Признак подписки"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите курс подписки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscourse",
                        to="materials.course",
                        verbose_name="Подписка на курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя подписки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsuser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь подписки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
