# Generated by Django 5.1.3 on 2024-11-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку для оплаты",
                max_length=400,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="status_pay",
            field=models.CharField(
                blank=True,
                help_text="Укажите статус оплаты",
                max_length=20,
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите урок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
