# Generated by Django 5.1.3 on 2024-11-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку для оплаты",
                max_length=1000,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
    ]
